name = "LazyStrings"
uuid = "011382f2-1ba6-4494-bbc4-494973ed13c8"
authors = ["Gregor Kappler"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
